#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=90
INTERFACE=br-lan
PORT=1337

# check if configuration exists
[ -e "/etc/redsocks.conf" ] || exit 0

nftables_start() {
    /bin/echo -n "running proxy bypass nftables ..."

    # Run iptable commands
    nft add chain ip nat REDSOCKS

    nft add rule ip nat REDSOCKS ip daddr 0.0.0.0/8 counter return
    nft add rule ip nat REDSOCKS ip daddr 10.0.0.0/8 counter return
    nft add rule ip nat REDSOCKS ip daddr 127.0.0.0/8 counter return
    nft add rule ip nat REDSOCKS ip daddr 169.254.0.0/16 counter return
#    nft add rule ip nat REDSOCKS ip daddr 172.16.0.0/12 counter return
    nft add rule ip nat REDSOCKS ip daddr 192.168.0.0/16 counter return
    nft add rule ip nat REDSOCKS ip daddr 224.0.0.0/4 counter return
    nft add rule ip nat REDSOCKS ip daddr 240.0.0.0/4 counter return

    nft add rule ip nat REDSOCKS ip protocol tcp counter redirect to :${PORT}

    nft add rule ip nat PREROUTING iifname "${INTERFACE}" ip protocol tcp counter jump REDSOCKS

    nft add rule ip filter INPUT iifname "${INTERFACE}" tcp dport ${PORT} counter accept

    /bin/echo " done"
}

nftables_stop() {
    /bin/echo -n "cleaning proxy bypass nftables ..."

    # Run iptable commands
    nft delete rule ip nat PREROUTING handle $(nft -a list chain ip nat PREROUTING | grep "jump REDSOCKS" | grep -o 'handle [0-9]*' | grep -o '[0-9]*$') && nft delete chain ip nat REDSOCKS && nft delete rule ip filter INPUT handle $(nft -a list chain ip filter INPUT | grep "dport ${PORT}" | grep -o 'handle [0-9]*' | grep -o '[0-9]*$')

    /bin/echo " done"
}

start() {
    if [ -e "/var/run/redsocks.pid" ]; then
        echo "proxy bypass is already running"
        exit 0
    fi

    /bin/echo -n "running proxy bypass ..."

    # startup the safety-wrapper for the daemon
    /usr/sbin/redsocks -c /etc/redsocks.conf -p /var/run/redsocks.pid

    /bin/echo " done"
    nftables_start
}


stop() {
    if [ ! -e "/var/run/redsocks.pid" ]; then
        echo "proxy bypass is not running"
        exit 0
    fi

    /bin/echo -n "stopping proxy bypass ..."

    # kill the process
    /bin/kill $(cat /var/run/redsocks.pid)
    rm /var/run/redsocks.pid

    echo " done"
    nftables_stop

    /bin/echo -n "restarting firewall ..."
    /etc/init.d/firewall restart &> /dev/null
    /bin/echo " done"
}
